### ISSUE TITLE
"mfa_token is not defined" when attempting to assume role

### ISSUE THREAD

**Issue by dlo** [coinbase/assume-role#5]
Hi all, thanks for this project!

When I run `assume-role production read`, I receive the following error:

```
echo "mfa_token is not defined";
```

Providing the MFA token after `read`, it does work, but this behavior appears to contradict the README.

**Comment by krobertson** [comment]
How are you running it?  Are you running it directly, or did you do `source $(which assume-role)`?

You should source it in, since running it, it can't export the env vars to the parent process. Running it directly, it assumes you're providing everything on the command line and going to `eval` the result.

**Comment by grahamjenson** [comment]
Yes to get interactive input, you will need to `source` the script.
