### ISSUE TITLE
Does not work without MFA

### ISSUE THREAD

**Issue by qoomon** [coinbase/assume-role#9]
script Does not work without MFA.
```shell
assume-role 123456789012 Administrator
echo "mfa_token is not defined";
```

**Comment by grahamjenson** [comment]
This issue might be caused by:
1. You not sourcing the script in your `.rc` file. If you don't then you have to use the script like `assume-role 123456789012 Administrator 000000`
2. You not wanting to use MFA with `assume-role`

If you do not want to use MFA, then unfortunately `assume-role` will not be implemented to be used without MFA. At coinbase we think using MFA is the default good security practice, so will not add an option to remove it, sorry.  But feel free to fork and remove the MFA checking code.
